### ISSUE TITLE
Cannot run java 17

### ISSUE THREAD

**Issue by Ygarr** [HanSolo/SpaceFX#13]
java -jar SpaceFX-windows-17.0.0.jar
Error: LinkageError occurred while loading main class eu.hansolo.spacefx.Launcher
        java.lang.UnsupportedClassVersionError: eu/hansolo/spacefx/Launcher (class file version 60.65535) was compiled with preview features that are unsupported. This version of the Java Runtime only recognizes preview features for class file version 61.65535
        
$java -version
openjdk version "17.0.4" 2022-07-19 LTS
OpenJDK Runtime Environment Zulu17.36+13-CA (build 17.0.4+8-LTS)
OpenJDK 64-Bit Server VM Zulu17.36+13-CA (build 17.0.4+8-LTS, mixed mode, sharing)

**Comment by HanSolo** [comment]
Will look into this tomorrow 👍🏻

**Comment by HanSolo** [comment]
I've removed the preview settings from the build file and tested it on my Mac and it works perfectly fine here with the same JDK version that you use. So please let me know if it works for you too with the latest commit in master.

**Comment by Ygarr** [comment]
Ok, thank you now it works.
