### ISSUE TITLE
Strange behaviour of in-game controls

### ISSUE THREAD

**Issue by Ygarr** [HanSolo/SpaceFX#14]
Before press left or right need to release all previous button like you drive with one finger. 

Use case
1. You moving left
2.  then moving right(finger from left button not removed, or removed later while moving right)
3.  trying to move left but spaceship just stopped even you still press left and Game waiting for when you release all buttons.

**Comment by HanSolo** [comment]
You should play it with the mouse. Drag the spaceship with the mouse and shoot with 'Space' and 'R'. It's not made for continues movement via keyboard.
