### ISSUE TITLE
Screen moving

### ISSUE THREAD

**Issue by Ygarr** [HanSolo/SpaceFX#15]
Launched game in MS Windows has a big screen. So cannot see top and bottom borders

When trying to look where borders of game window ends usually used Alt+mouseLeft button and then moving. 
But this option does not work for this window

UPD: other windows in MSWin seems also do not moving. So in would be great to change in-game window resolution.

**Comment by HanSolo** [comment]
The desktop version is running with a fixed resolution of 700x900 px which works fine on my windows machine. The game is not scaleable and can also not run in full screen. You have to think about an Arcade machine with a fixed resolution. In addition this is just a demo and not a commercial game. :)
